### ISSUE TITLE
 Right-hand side of 'instanceof' is not an object

### ISSUE THREAD

**Issue by pavankumarkatakam** [extractr-io/puphpeteer#3] opened 2018-03-29 11:06 UTC
Hi,
 Im getting the below-mentioned error, please check and clarify
 "**Right-hand side of 'instanceof' is not an object**" (In Process.php line 230:)
When I turn on the debug true,
```
TypeError: Right-hand side of 'instanceof' is not an object                                                                                
      at PuppeteerConnectionDelegate.handleInstruction (/media/administrator/Storage/Projects/vp/BssApi/vendor/extractr-io/puphpeteer/src/P  
  uppeteerConnectionDelegate.js:44:19)                                                                                                       
      at <anonymous>                                                                                                                         
      at process._tickCallback (internal/process/next_tick.js:188:7)
```

I actually removed the lines instance of Brower checking and it is working fine.

My Environment details
1. ubunto os: 16.04
2. PHP: 7.1.15
3. Node: 8.9.3 (NPM: 5.6.0)

**Comment by nesk** [comment] 2018-03-29 13:02
Coul you please give me a reproducible example?

**Comment by pavankumarkatakam** [comment] 2018-03-29 13:30
Im using this in the laravel project -> commands (console), below is my handle function

```
        $puppeteer = new Puppeteer([
            'read_timeout' => 100,
            'debug' => env('APP_DEBUG')
        ]);
        $browser = $puppeteer->launch([
            'headless' => env('APP_DEBUG'),
            'ignoreHTTPSErrors' => true
        ]);

        $page = $browser->newPage();
        $page->setViewport(['width' => 1920, 'height' => 1080]);

        // Login first
        $page->goto('http://xxxxxx.in/home.do#', ['waitUntil' => 'networkidle2']);
        $page->type('.loginEmail', env('xxxxxx_USERNAME'));
        $page->type('.loginPassword', env('xxxxx_PASSWORD'));
        $page->click("#login input[type='submit']");
        $page->waitForNavigation();
```

**Comment by egifford** [comment] 2018-04-11 19:30
I think this project is really cool, but I'm getting the same error as the OP.

Here is my configuration:
- Windows 10 Pro
- Running in Git for Windows bash (version 2.16.0.windows.2)
- PHP 7.1.16 (cli) (built: Mar 28 2018 21:15:22) ( NTS MSVC14 (Visual C++ 2015) x64 )
- Node v8.9.4

I'm using the 0.2.1 version of puphpeteer.

My PHP code is something like this:

```
$puppeteer = new Puppeteer(['debug' => true]);
$browser   = $puppeteer->launch();

$page = $browser->newPage();
$page->goto('https://example.com');
$page->screenshot(['path' => 'example.png']);

$browser->close();
```

My code is failing on the call to launch().

Here is the error I receive:
```
Fatal error: Uncaught ExtractrIo\Rialto\Exceptions\Node\FatalException: Right-hand side of 'instanceof' is not an object

TypeError: Right-hand side of 'instanceof' is not an object
    at PuppeteerConnectionDelegate.handleInstruction (vendor\extractr-io\puphpeteer\src\PuppeteerConnectionDelegate.js:42:19)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7) in vendor\extractr-io\rialto\src\ProcessSupervisor.php:230
Stack trace:
#0 vendor\extractr-io\rialto\src\ProcessSupervisor.php(322): ExtractrIo\Rialto\ProcessSupervisor->checkProcessStatus()
#1 vendor\extractr-io\rialto\src\ProcessSupervisor.php(285): ExtractrIo\Rialto\ProcessSupervisor->readNextProcessValue()
#2 vendor\extractr-io\rialto\src\Traits\CommunicatesWithProcessSupervisor.php(83): ExtractrIo\Rialto\ProcessSupervis in vendor\extractr-io\rialto\src\ProcessSupervisor.php on line 230
```

Let me know if you need any more information or want me to test something.

Thanks!

**Comment by nesk** [comment] 2018-04-13 08:39
Actually, I have a hard time reproducing the issue. Could you edit `vendor/extractr-io/puphpeteer/PuppeteerConnectionDelegate.js` in your project and add this code in line 41 (provide a valid file path in this code)?

```js
const filePath = '/path/to/a/safe/directory/to/write/debug.txt';
require('fs').writeFileSync(filePath, typeof Browser);
if (Browser && Browser.toString) require('fs').appendFileSync(filePath, '\n\n' + Browser.toString());
require('fs').appendFileSync(filePath, '\n\n' + JSON.stringify(Browser));
```

Then run `(new \ExtractrIo\Puphpeteer\Puppeteer)->launch()` in PHP and send me the contents of the generated `debug.txt` file.

**Comment by nesk** [comment] 2018-04-19 09:55
Thank you for your help @egifford, I'm starting to understand what's happening. NVM is probably what causes the issue. (@pavankumarkatakam, are you using NVM too?)

I will start working on a fix asap.

**Comment by pavankumarkatakam** [comment] 2018-04-19 12:04
Yes, I'm using the NVM. In this context, my NVM points to 8.9.3 NodeJs version.

**Comment by nesk** [comment] 2018-04-19 14:29
I've created a branch to support NVM in Rialto and PuPHPeteer, it would be great if both of you could clone [this repository](https://github.com/nesk/puphpeteer-nvm-support) and run the following commands (use the same environment as before):

```shell
composer install
npm install
php run.php
```

The latest command should output `OK`, otherwise you will get an error, if its the case copy/paste it here.

**Comment by nesk** [comment] 2018-04-19 14:47
ooh! Actually, it could be **much** simpler! Could you tell what's returned by `npm list --depth=0` when you this command in your original projects? (not in my custom repository just above)

I've just found that PuPHPeteer doesn't work with Puppeteer v1.2+ with exactly the same error as you, so I wnat to check the version you're using.

**Comment by egifford** [comment] 2018-04-19 15:35
For the test project, I received OK as output.

For npm list --depth=0:
```
C:\Work\projects\BusinessSkills.D7\project\tools\testing
+-- @extractr-io/puphpeteer@0.2.1
`-- puppeteer@1.3.0
```

**Comment by egifford** [comment] 2018-04-19 16:17
I think you are correct that the Puppeteer version was causing my issue.  I did a clean install with composer and npm, made sure I had puppeteer@1.1.1, and my screenshot script worked perfectly.

Before I found PuPHPeteer, I was evaluating [spatie/browsershot](https://github.com/spatie/browsershot) and must have still had a newer version of puppeteer installed.

This project is really good.  I hope I didn't take too much of your time to resolve this.

If you decide to setup a project funding mechanism, like Patreon, I'd contribute some USDs.  Though it looks like you might have some funding via a startup.  Anyway, good luck!

**Comment by pavankumarkatakam** [comment] 2018-04-20 09:12
For npm list --depth=0
```
/media/XXXX/Storage/Projects/vp/XXXX
+-- @extractr-io/puphpeteer@0.2.0
+-- @extractr-io/rialto@0.1.1
+-- axios@0.16.2
+-- bootstrap-sass@3.3.7
+-- cross-env@5.0.5
+-- foundation-emails@2.2.1
+-- gulp@3.9.1
+-- ioredis@1.15.1
+-- jquery@3.2.1
+-- laravel-echo-server@1.3.6
+-- laravel-elixir@6.0.0-17
+-- laravel-elixir-foundation-emails@1.0.4
+-- laravel-mix@1.4.5
+-- lodash@4.17.4
+-- puppeteer@1.2.0
+-- underscore@1.8.3
+-- uws@9.14.0
`-- vue@2.4.4
```
For the test project, I received below output.

```
PHP Fatal error:  Uncaught Symfony\Component\Process\Exception\ProcessFailedException: The command "'node' '/home/administrator/Practise/puphpeteer-nvm-support/vendor/extractr-io/rialto/src/node-process/serve.js' '/home/administrator/Practise/puphpeteer-nvm-support/vendor/extractr-io/puphpeteer/src/PuppeteerConnectionDelegate.js' '{"idle_timeout":60}'" failed.

Exit Code: 1(General error)

Working directory: /home/administrator/Practise/puphpeteer-nvm-support

Output:
================


Error Output:
================
module.js:538
    throw err;
    ^

Error: Cannot find module 'puppeteer'
    at Function.Module._resolveFilename (module.js:536:15)
    at Function.Module._load (module.js:466:25)
    at Module.require (module.js:579:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/administrator/Practise/puphpeteer-nvm-support/vendor/extractr-io/puphpeteer/src/PuppeteerConnectionDelegate.js:3:19)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at  in /home/administrator/Practise/puphpeteer-nvm-support/vendor/extractr-io/rialto/src/ProcessSupervisor.php on line 232

```

**Comment by nesk** [comment] 2018-04-20 14:10
Version 0.2.2 is now available and supports Puppeteer v1.3+. Additionnally, from now you will be warn in the logs if the installed version of Puppeteer doesn't match the requirements. 😉

Since it should be solved, I'm closing the issue.

**Closed by nesk** 2018-04-20 14:10 UTC

**Comment by 7starsone** [comment] 2018-06-06 14:56
Hello, I get on php error log

`PHP Fatal error:  Uncaught Nesk\Rialto\Exceptions\Node\FatalException: Right-hand side of 'instanceof' is not callable in /home/myuser/public_html/tmp/pjs/vendor/nesk/rialto/src/ProcessSupervisor.php:230`

**Comment by nesk** [comment] 2018-06-06 15:39
Paste here the logs emitted by PuPHPeteer, you can obtain them by using [the `logger` option in the constructor](https://github.com/nesk/rialto/blob/master/docs/api.md#options).

**Comment by nesk** [comment] 2018-06-07 13:03
@7starsone If necessary, I've just created [a guide to help you providing logs](https://github.com/nesk/puphpeteer/blob/master/.github/contributing.md#provide-logs-with-your-bug-report).

**Comment by 7starsone** [comment] 2018-06-07 14:56
```
[2018-06-07 16:53:14] PuPHPeteer.WARNING: The installed version of Puppeteer (v1.1.1) doesn't match the requirements (~1.4.0), you may encounter issues. [] []
[2018-06-07 16:53:14] PuPHPeteer.DEBUG: [options] {"read_timeout":35,"logger":{}} [] []
[2018-06-07 16:53:14] PuPHPeteer.DEBUG: Starting process... [] []
[2018-06-07 16:53:14] PuPHPeteer.DEBUG: [PID 482] Process started [] []
[2018-06-07 16:53:14] PuPHPeteer.DEBUG: [PORT 33505] [sending] {"type":"call","name":"launch","catched":false,"value":[{"args":["--no-sandbox","--disable-setuid-sandbox"]}]} [] []
[2018-06-07 16:53:14] PuPHPeteer.DEBUG: [PORT 33505] [receiving]  [] []
[2018-06-07 16:53:14] PuPHPeteer.ERROR: [PID 482] [stderr] {"__rialto_error__":true,"message":"Right-hand side of 'instanceof' is not callable","stack":"TypeError: Right-hand side of 'instanceof' is not callable\n    at PuppeteerConnectionDelegate.handleInstruction (/home/myuser/public_html/tmp/pjs/vendor/nesk/puphpeteer/src/PuppeteerConnectionDelegate.js:42:19)\n    at <anonymous>\n    at process._tickCallback (internal/process/next_tick.js:182:7)"} [] []
```
so, is it about a _Puppeteer_ update? I thought that
```
composer require nesk/puphpeteer
npm install @nesk/puphpeteer 
```
was enough to update _Puppeteer_. So, how to update it, instead?
Thanks

**Comment by nesk** [comment] 2018-06-07 15:00
Ah! I knew it! 😁

You have to run `npm update @nesk/puphpeteer`. If it doesn't work, try deleting the `node_modules` directory and run `npm update`.

**Comment by 7starsone** [comment] 2018-06-07 15:35
that's fixed now but always an issue about the page content
eg. URL https://icecat.de/search?keyword=ie-3000-8tc
the `var_dump($page->content());` doesn't retrieve the container on the center, eg. the class **_3rsz9QKOF3v-TD6wzRdTxc** in this case.
What's the reason, please?
thanks

**Comment by nesk** [comment] 2018-06-07 15:46
Probably because you're trying to read the content before the JS has finished to retrieve the server data. Try to use the following method: [`page.waitFor(selectorOrFunctionOrTimeout[, options[, ...args]])`](https://github.com/GoogleChrome/puppeteer/blob/v1.4.0/docs/api.md#pagewaitforselectororfunctionortimeout-options-args).

If you have more questions about this, please [head over to StackOverflow](https://stackoverflow.com/questions/tagged/puppeteer), because this doesn't seem to be related to a bug in PuPHPeteer or Puppeteer.

**Comment by 7starsone** [comment] 2018-06-07 16:47
yes, the `waitFor` could be useful for a selector but if the content is dynamically loaded the real solution
in this case is something like
```
$response = $page->goto($url, [
    'waitUntil' => 'networkidle0', 
]);
```
it works, I didn't try other options there but for now is good as it is....
thank you very much
